from builtins import Exception


class EmptyResult(Exception):
    pass